update colors and make root user red

diff --git a/home/.bashrc.d/promtline b/home/.bashrc.d/promtline
--- a/home/.bashrc.d/promtline
+++ b/home/.bashrc.d/promtline
@@ -11,39 +11,39 @@ function __promptline_last_exit_code {
 function __promptline_ps1 {
   local slice_prefix slice_empty_prefix slice_joiner slice_suffix is_prompt_empty=1
 
-  # section "a" header
+  # section "a" header (host)
   slice_prefix="${a_bg}${sep}${a_fg}${a_bg}${space}" slice_suffix="$space${a_sep_fg}" slice_joiner="${a_fg}${a_bg}${alt_sep}${space}" slice_empty_prefix="${a_fg}${a_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "a" slices
-  __promptline_wrapper "$([[ -n ${ZSH_VERSION-} ]] && print %m || { [[ -n ${SSH_CLIENT} ]] && printf " %s" \\h; })" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
+  __promptline_wrapper "$([[ -n ${ZSH_VERSION-} ]] && print %m || { [[ -n ${SSH_CLIENT} || "${USER}" = "root" ]] && printf " %s" \\h; })" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
 
-  # section "b" header
+  # section "b" header (username)
   slice_prefix="${b_bg}${sep}${b_fg}${b_bg}${space}" slice_suffix="$space${b_sep_fg}" slice_joiner="${b_fg}${b_bg}${alt_sep}${space}" slice_empty_prefix="${b_fg}${b_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "b" slices
   __promptline_wrapper "\u" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
 
-  # section "c" header
+  # section "c" header (virtual env)
   slice_prefix="${c_bg}${sep}${c_fg}${c_bg}${space}" slice_suffix="$space${c_sep_fg}" slice_joiner="${c_fg}${c_bg}${alt_sep}${space}" slice_empty_prefix="${c_fg}${c_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "c" slices
   __promptline_wrapper "${VIRTUAL_ENV##*/}" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
 
-  # section "x" header
+  # section "x" header (git)
   slice_prefix="${x_bg}${sep}${x_fg}${x_bg}${space}" slice_suffix="$space${x_sep_fg}" slice_joiner="${x_fg}${x_bg}${alt_sep}${space}" slice_empty_prefix="${x_fg}${x_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "x" slices
   __promptline_wrapper "$(__promptline_vcs_branch)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
   __promptline_wrapper "$(__promptline_git_status)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
 
-  # section "y" header
+  # section "y" header (path)
   slice_prefix="${y_bg}${sep}${y_fg}${y_bg}${space}" slice_suffix="$space${y_sep_fg}" slice_joiner="${y_fg}${y_bg}${alt_sep}${space}" slice_empty_prefix="${y_fg}${y_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "y" slices
   __promptline_wrapper "$(__promptline_cwd)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
   __promptline_wrapper "$(__promptline_jobs)" "$slice_prefix" "$slice_suffix" && { slice_prefix="$slice_joiner"; is_prompt_empty=0; }
 
-  # section "warn" header
+  # section "warn" header (exit code)
   slice_prefix="${warn_bg}${sep}${warn_fg}${warn_bg}${space}" slice_suffix="$space${warn_sep_fg}" slice_joiner="${warn_fg}${warn_bg}${alt_sep}${space}" slice_empty_prefix="${warn_fg}${warn_bg}${space}"
   [ $is_prompt_empty -eq 1 ] && slice_prefix="$slice_empty_prefix"
   # section "warn" slices
@@ -229,24 +229,29 @@ function __promptline {
   local alt_rsep=""
   local reset="${wrap}0${end_wrap}"
   local reset_bg="${wrap}49${end_wrap}"
-  local a_fg="${wrap}38;5;15${end_wrap}"
-  local a_bg="${wrap}48;5;10${end_wrap}"
-  local a_sep_fg="${wrap}38;5;10${end_wrap}"
-  local b_fg="${wrap}38;5;15${end_wrap}"
-  local b_bg="${wrap}48;5;4${end_wrap}"
-  local b_sep_fg="${wrap}38;5;4${end_wrap}"
+  local a_fg="${wrap}38;5;231${end_wrap}"
+  local a_bg="${wrap}48;5;242${end_wrap}"
+  local a_sep_fg="${wrap}38;5;242${end_wrap}"
+  local b_fg="${wrap}38;5;231${end_wrap}"
+  if [ "${USER}" = "root" ]; then
+    local b_bg="${wrap}48;5;9${end_wrap}"
+    local b_sep_fg="${wrap}38;5;9${end_wrap}"
+  else
+    local b_bg="${wrap}48;5;69${end_wrap}"
+    local b_sep_fg="${wrap}38;5;69${end_wrap}"
+  fi
   local c_fg="${wrap}38;5;15${end_wrap}"
-  local c_bg="${wrap}48;5;2${end_wrap}"
+  local c_bg="${wrap}48;5;3${end_wrap}"
   local c_sep_fg="${wrap}38;5;2${end_wrap}"
   local warn_fg="${wrap}38;5;231${end_wrap}"
-  local warn_bg="${wrap}48;5;52${end_wrap}"
-  local warn_sep_fg="${wrap}38;5;52${end_wrap}"
-  local x_fg="${wrap}38;5;14${end_wrap}"
-  local x_bg="${wrap}48;5;0${end_wrap}"
-  local x_sep_fg="${wrap}38;5;0${end_wrap}"
-  local y_fg="${wrap}38;5;7${end_wrap}"
-  local y_bg="${wrap}48;5;10${end_wrap}"
-  local y_sep_fg="${wrap}38;5;10${end_wrap}"
+  local warn_bg="${wrap}48;5;9${end_wrap}"
+  local warn_sep_fg="${wrap}38;5;9${end_wrap}"
+  local x_fg="${wrap}38;5;231${end_wrap}"
+  local x_bg="${wrap}48;5;16${end_wrap}"
+  local x_sep_fg="${wrap}38;16;0${end_wrap}"
+  local y_fg="${wrap}38;5;231${end_wrap}"
+  local y_bg="${wrap}48;5;242${end_wrap}"
+  local y_sep_fg="${wrap}38;5;242${end_wrap}"
   if [[ -n ${ZSH_VERSION-} ]]; then
     PROMPT="$(__promptline_left_prompt)"
     RPROMPT="$(__promptline_right_prompt)"
